{
  "openapi": "3.0.3",
  "info":{
    "title":"API Veterinary Clinic",
    "description": "This API aims to register tutors and pets",
    "termsOfService": "",
    "contact":{
      "email": "vanessaoliveiradasilva515@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "",
      "description": "API test"
    }
  ],
  "paths": {
    "/tutor":{
      "post":{
        "sumary": "Cadastro de tutor",
        "description": "Rota responsável por cadastrar novo tutor",
        "tags": ["Tutor"],
        "requestBody": {
          "content":{
            "application/json":{
              "schema":{
                "$ref": "#/components/schemas/responseTutorPost"
              },
              "examples":{
                "tutor":{
                  "value":{
                    "name": "Vanessa Oliveira",
                    "password": "vanessa846795",
                    "phone": 69991458726,
                    "email": "vanessa@gmail.com",
                    "date_of_birth": "10-08-2003",
                    "zip_code": 84756900
                  }
                }
              }
            }
          }
        },
        "responses": {
          "500":{
            "description": "Internal_Server_Error"
          },
          "201":{
            "description": "Created",
            "content":{
              "application/json":{
                "schema":{
                  "type": "object",
                  "$ref":"#/components/schemas/Tutor"
                }
              }
            }
          }
        }
      }
    },
    "/tutor/{Id}":{
      "put":{
        "sumary": "Atualização de tutor",
        "description": "Rota responsável por atualizar um tutor pelo ID",
        "tags": ["Tutor"],
        "security": [{"bearerAuth": []}],
        "parameters":[
          {
            "name": "Id",
            "in": "path",
            "description":"Atualização do tutor pelo ID",
            "required": true
          }
        ],
        "requestBody": {
          "content":{
            "application/json":{
              "schema":{
                "$ref": "#/components/schemas/responseTutor"
              },
              "examples":{
                "tutor":{
                  "value":{
                    "id": "48171459-c9a2-4d94-8839-57ef73ec3f58",
                    "name": "Lana Silva",
                    "phone": 69991458726,
                    "email": "lana_silva@gmail.com",
                    "date_of_birth": "10-08-2003",
                    "zip_code": 84756900
                  }
                }
              }
            }
          }
        },
        "responses": {
          "404":{
            "description": "Bad_Request"
          },
          "500":{
            "description": "Internal_Server_Error"
          },
          "200":{
            "description": "Ok",
            "content":{
              "application/json":{
                "schema":{
                  "type": "object",
                  "$ref":"#/components/schemas/Tutor"
                }
              }
            }
          }
        }
      },
      "delete":{
        "sumary": "Deleção de tutor",
        "description": "Rota responsável por deletar um tutor pelo ID",
        "tags": ["Tutor"],
        "security": [{"bearerAuth": []}],
        "parameters":[
          {
            "name": "Id",
            "in": "path",
            "description":"Deleção do tutor pelo ID",
            "required": true
          }
        ],
        "responses":{
          "204":{
            "description": "No_Content"
          },
          "404": {
            "description": "Bad_Request"
          }
        }
      }
    },
    "/pet/{tutorId}":{
      "post":{
        "sumary": "Cadastro de pet",
        "description": "Rota responsável por cadastrar novo pet ao Id de um tutor que  já existe",
        "tags": ["Pet"],
        "security": [{"bearerAuth": []}],
        "parameters":[
          {
            "name": "tutorId",
            "in": "path",
            "description":"Cadastro do pet no ID do tutor",
            "required": true
          }
        ],
        "requestBody": {
          "content":{
            "application/json":{
              "schema":{
                "$ref": "#/components/schemas/responsePet"
              },
              "examples":{
                "pet":{
                  "value":{
                    "name": "Lolo",
                    "species": "dog",
                    "carry": "p",
                    "weight": 5,
                    "date_of_birth": "10-08-2003"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "500":{
            "description": "Internal_Server_Error"
          },
          "404":{
            "description":"Bad_Request"
          },
          "201":{
            "description": "Created",
            "content":{
              "application/json":{
                "schema":{
                  "type": "object",
                  "$ref":"#/components/schemas/Pet"
                }
              }
            }
          }
        }
      }
    },
    "/pet/{petId}/tutor/{tutorId}":{
      "put":{
        "sumary": "Atualização de pet",
        "description": "Rota responsável por atualizar um pet pelo id",
        "tags": ["Pet"],
        "security": [{"bearerAuth": []}],
        "parameters":[
          {
            "name": "petId",
            "in": "path",
            "description":"Atualização do pet pelo ID próprio e do tutor",
            "required": true
          },
          {
            "name": "tutorId",
            "in": "path",
            "description":"Atualização do pet pelo ID próprio e do tutor",
            "required": true
          }
        ],
        "requestBody": {
          "content":{
            "application/json":{
              "schema":{
                "$ref": "#/components/schemas/responsePet"
              },
              "examples":{
                "pet":{
                  "value":{
                    "id": "48171459-c9a2-4d94-8839-57ef73ec3f58",
                    "name": "Puf",
                    "species": "cat",
                    "carry": "p",
                    "weight": 5,
                    "date_of_birth": "10-08-2003"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "404":{
            "description":"Bad_Request"
          },
          "500":{
            "description": "Internal_Server_Error"
          },
          "200":{
            "description": "Ok",
            "content":{
              "application/json":{
                "schema":{
                  "type": "object",
                  "$ref":"#/components/schemas/responsePet"
                }
              }
            }
          }
        }
      }
    },
    "/tutor/{tutorId}/pet/{petId}":{
      "delete":{
        "sumary": "Deleção de pet",
        "description": "Rota responsável por deletar um pet pelo ID",
        "tags": ["Pet"],
        "security": [{"bearerAuth": []}],
        "parameters":[
          {
            "name": "petId",
            "in": "path",
            "description":"Deleção do pet pelo ID próprio e do tutor",
            "required": true
          },
          {
            "name": "tutorId",
            "in": "path",
            "description":"Deleção do pet pelo ID próprio e do tutor",
            "required": true
          }
        ],
        "responses":{
          "204":{
            "description": "No_Content"
          },
          "400": {
            "description": "Bad_Request"
          }
        }
      }
    },
    "/tutor/pet":{
      "get":{
        "sumary": "Busca dos tutores",
        "description": "Busca de todos os tutores",
        "tags": ["Tutor"],
        "security": [{"bearerAuth": []}],
        "responses":{
          "200":{
            "description": "Ok",
            "content":{
              "application/json":{
                "schema":{
                  "type": "array",
                  "items":{
                    "$ref":"#/components/schemas/responseTutorGet"
                  }
                },
                "500":{
                  "description": "Internal_Server_Error"
                }
              }
            }
          }
        }
      }
    },
    "/auth":{
      "post":{
        "sumary":"Autenticação de um tutor",
        "description": "Autenticação de um tutor para gerar um token",
        "tags":["Auth"],
        "requestBody": {
          "content":{
            "application/json":{
              "schema":{
                "$ref": "#/components/schemas/createWebtoken"
            },
            "examples":{
              "pet":{
                "value":{
                  "email": "vanessa@gmail.com",
                  "password": "vanesa45454"
                }
              }
            }
          }
        }
      },
      "responses":{
        "401":{
          "description": "Unauthorized"
        },
        "200":{
          "description": "Ok",
          "content":{
            "application/json":{
              "schema":{
                "type": "object",
                "items":{
                  "$ref":"#/components/schemas/createWebtoken"
                }
            }
          }
        }
      },
      "500":{
        "description": "Internal_Server_Error"
        }
      }
    }
  }
  },
  "components":{
    "schemas":{
      "Tutor":{
        "type": "object",
        "properties":{
          "id":{
            "type": "uuid"
          },
          "name":{
            "type": "string"
          },
          "password":{
            "type":"string"
          },
          "phone":{
            "type": "number"
          },
          "email":{
            "type":"string"
          },
          "date_of_birth":{
            "type":"date"
          },
          "zip_code":{
            "type":"number"
          }
        }
      },
      "responseTutorGet":{
        "type": "object",
        "properties":{
          "id":{
            "type":"uuid"
          },
          "name":{
            "type": "string"
          },
          "phone":{
            "type": "number"
          },
          "email":{
            "type":"string"
          },
          "date_of_birth":{
            "type":"date"
          },
          "zip_code":{
            "type":"number"
          }
        }
      },
      "responseTutorPost":{
        "type": "object",
        "properties":{
          "name":{
            "type": "string"
          },
          "password":{
            "type":"string"
          },
          "phone":{
            "type": "number"
          },
          "email":{
            "type":"string"
          },
          "date_of_birth":{
            "type":"date"
          },
          "zip_code":{
            "type":"number"
          }
        }
      },
      "responseTutor":{
        "type": "object",
        "properties":{
          "name":{
            "type": "string"
          },
          "phone":{
            "type": "number"
          },
          "email":{
            "type":"string"
          },
          "date_of_birth":{
            "type":"date"
          },
          "zip_code":{
            "type":"number"
          }
        }
      },
      "Pet":{
        "type": "object",
        "properties":{
          "id":{
            "type": "uuid"
          },
          "name":{
            "type": "string"
          },
          "species":{
            "type":"string"
          },
          "carry":{
            "type": "string"
          },
          "weight":{
            "type":"number"
          },
          "date_of_birth":{
            "type":"date"
          }
        }
      },
      "responsePet":{
        "type": "object",
        "properties":{
          "name":{
            "type": "string"
          },
          "species":{
            "type":"string"
          },
          "carry":{
            "type": "string"
          },
          "weight":{
            "type":"number"
          },
          "date_of_birth":{
            "type":"date"
          }
        }
      },
      "createWebtoken":{
        "type": "object",
        "properties":{
          "email":{
            "type": "string"
          },
          "password":{
            "type":"string"
          }
        }
      }
    },
    "securitySchemes":{
      "bearerAuth":{
        "description": "Autenticação usando JWT",
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}